### ISSUE TITLE
What is the correct input-output mapping for IL ?

### ISSUE THREAD

**Issue by jrabary** [duckietown/AIDO18_baselines#3]
I notice that the content of the rosbag used in Pytorch and TF implentation of the IL algorithm is not exactly the same. In the pytorch implementation the network predicts left-right velocity and in the TF implementation it predicts the omega. Why this difference ?

**Comment by jzilly** [comment]
The more robust solution will be to predict left-right velocity. The TF implementation is based on the assumption that a (PID) controller picks up the omega commands and converts it into left-right velocity. 

Thank you for spotting this. Will adjust it to work on left-right velocity.

**Comment by jrabary** [comment]
@julian121266 Thanks for your reply. Just to understand better. In the documentation it is said that 
```
Outputs (what your machine learning agent has to produce/learn): 
One pair of motor commands per timestep in the form of (v,omega), 
where v = continuous velocity in range [-1,1] corresponding to maximum power backwards
 (-1) and maximum power forward (+1) and omega = continuous steering angle in range [-1,1] 
corresponding to hard left steering (-1) and hard right steering (+1). 
The robot has a minimum turn radius that is automatically taken 
into account, i.e. if you try to do something like (0,1) or (0,-1) 
the robot will not rotate in-place.
```

And in the class Duckietownenv the step function does take the velocity and omega : 

```
def step(self, action):
        vel, angle = action

        # Distance between the wheels
        baseline = self.unwrapped.wheel_dist

        # assuming same motor constants k for both motors
        k_r = self.k
        k_l = self.k

        # adjusting k by gain and trim
        k_r_inv = (self.gain + self.trim) / k_r
        k_l_inv = (self.gain - self.trim) / k_l

        omega_r = (vel + 0.5 * angle * baseline) / self.radius
        omega_l = (vel - 0.5 * angle * baseline) / self.radius

        # conversion from motor rotation rate to duty cycle
        u_r = omega_r * k_r_inv
        u_l = omega_l * k_l_inv

        # limiting output to limit, which is 1.0 for the duckiebot
        u_r_limited = max(min(u_r, self.limit), -self.limit)
        u_l_limited = max(min(u_l, self.limit), -self.limit)

        vels = np.array([u_l_limited, u_r_limited])

        return super().step(vels)
```
Then, it is not just clear why would you sent to the robot the left-right velocity ?

**Comment by jzilly** [comment]
Dear @jrabary, 
This is the current implementation. Currently we are trying to make the simulator more and more like the real Duckiebots, which also entails using voltage commands to the actuators rather than velocities as outputs. Thus the descriptions above are currently correct but will be updated in the (hopefully) near future.

**Comment by jzilly** [comment]
Dear @jrabary,
We are moving this repository to this address: https://github.com/duckietown/challenge-aido1_LF1-baseline-IL-logs-tensorflow 
For further use, please use this as a baseline to start from. Everything should currently. If something does not work, please make an issue and I will work on it.
