### ISSUE TITLE
Make preprocess issue

### ISSUE THREAD

**Issue by darrentde** [duckietown/AIDO18_baselines#4]
I am having trouble trying to run the make preprocess after downloading the logs. The error below is what I got. 

make preprocess
. LF_IL_pytorch_virtualenv/bin/activate; \
			python src/extract_data.py -s logdir -t datadir;
Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
Extracting images for /home/darren/AIDO18_baselines/tasks/AIDO18_E_LF1_PIM/LF_IL_pytorch/logdir/20180108141006_a313.bag
failed to open /home/darren/AIDO18_baselines/tasks/AIDO18_E_LF1_PIM/LF_IL_pytorch/logdir/20180108141006_a313.bag
Extracting images for /home/darren/AIDO18_baselines/tasks/AIDO18_E_LF1_PIM/LF_IL_pytorch/logdir/20180108135529_a313.bag
Extracting images for /home/darren/AIDO18_baselines/tasks/AIDO18_E_LF1_PIM/LF_IL_pytorch/logdir/20180108141448_a313.bag
failed to open /home/darren/AIDO18_baselines/tasks/AIDO18_E_LF1_PIM/LF_IL_pytorch/logdir/20180108141448_a313.bag
Extracting images for /home/darren/AIDO18_baselines/tasks/AIDO18_E_LF1_PIM/LF_IL_pytorch/logdir/20180108141719_a313.bag
failed to open /home/darren/AIDO18_baselines/tasks/AIDO18_E_LF1_PIM/LF_IL_pytorch/logdir/20180108141719_a313.bag

Next, I tried to check if there were any problems with the bag files and turns out there were some rules missing in the bag files. 

rosbag check  20180108135529_a313.bag

The following migrations need to occur:
 * From: duckietown_msgs/Twist2DStamped [3fc0942a3082e78d7ded4a58ea1e2d0c]
   To:   Unknown
    1 rules missing:
     * From: duckietown_msgs/Twist2DStamped [3fc0942a3082e78d7ded4a58ea1e2d0c]
       To:   Unknown
 * From: duckietown_msgs/FSMState [7358237ec6ffa8d862869f9b95659ac9]
   To:   Unknown
    1 rules missing:
     * From: duckietown_msgs/FSMState [7358237ec6ffa8d862869f9b95659ac9]
       To:   Unknown
 * From: duckietown_msgs/BoolStamped [542e22b190dc8e6eb476d50dda88feb7]
   To:   Unknown
    1 rules missing:
     * From: duckietown_msgs/BoolStamped [542e22b190dc8e6eb476d50dda88feb7]
       To:   Unknown
 * From: duckietown_msgs/LanePose [4124b9e06f7f0e9603fe7046ce2b93b0]
   To:   Unknown
    1 rules missing:
     * From: duckietown_msgs/LanePose [4124b9e06f7f0e9603fe7046ce2b93b0]
       To:   Unknown
 * From: duckietown_msgs/AntiInstagramTransform [d8691e07ae6615fec4d91101863288cf]
   To:   Unknown
    1 rules missing:
     * From: duckietown_msgs/AntiInstagramTransform [d8691e07ae6615fec4d91101863288cf]
       To:   Unknown
 * From: duckietown_msgs/SegmentList [1cefc32a4bc9039bf09d40c6c13beace]
   To:   Unknown
    1 rules missing:
     * From: duckietown_msgs/SegmentList [1cefc32a4bc9039bf09d40c6c13beace]
       To:   Unknown
 * From: duckietown_msgs/WheelsCmdStamped [edbf8d24194d839b1982a6a991b552c6]
   To:   Unknown
    1 rules missing:
     * From: duckietown_msgs/WheelsCmdStamped [edbf8d24194d839b1982a6a991b552c6]
       To:   Unknown
 * From: duckietown_msgs/AntiInstagramHealth [3a6e17ea173536e892b4dde76e515fb4]
   To:   Unknown
    1 rules missing:
     * From: duckietown_msgs/AntiInstagramHealth [3a6e17ea173536e892b4dde76e515fb4]
       To:   Unknown

Is there a way to get around this issue or is it just a bug in the bag files? Thanks

**Comment by jzilly** [comment]
What we have done in the meantime is migrate this code into a new repository (https://github.com/duckietown/challenge-aido1_LF1-baseline-IL-logs-tensorflow). However at this point only the Tensorflow part is supported. Unfortunately it is much easier to run the code on the physical Duckiebots using Tensorflow rather than Pytorch. Until this changes, we will focus on the Tensorflow implementation.
